### ISSUE TITLE
The issue of imbalanced raw data

### ISSUE THREAD

**Issue by wangyingyu1993** [UnixJunkie/FASMIFRA#37]
The distribution of my molecular types is imbalance. For instance, Type A molecules are crucial but scarce in number. When generating new molecules, how can I ensure that the new generated molecules based on Type A molecules occupy a relatively high proportion? If I first generate molecules based on Type A molecules (personally, I wonder if the extracted substituents will be too few, leading to a lack of diversity in the generated molecules?), and then merge them into the overall dataset before proceeding with further molecular generation, is this approach feasible?

**Comment by UnixJunkie** [comment]
Can you give a number?
If "too few" is like a handful molecules, yes this is risky.
If "too few" is like 50, then it is not so risky.

If you fragment molecules using BRICS (in the github repository, w/ corrections from yesterday!), it might give you more fragments than the default algorithm.
Or, use the default fragmentation algorithm, but use a small value for -w (like 50; meaning 50 Da) to get more fragments.

So:
fasmifra_fragment.py --brics -i few_mols.smi -o few_mols_BRICS.smi
OR
fasmifra_fragment.py -w 50 -i few_mols.smi -o few_mols_small_frags.smi

Also, when you generate molecules, generate a lot, in order to explore all fragments combinations.

I could implement an exhaustive sampler in FASMIFRA one day, maybe.

After having used fasmifra on your fragments file of choice,
you need to convert the generated molecules to canonical SMILES, then do unique filtering to get a set of varied molecules.

**Comment by wangyingyu1993** [comment]
Account for approximately 3%, or roughly 800 in terms of quantity.

**Comment by UnixJunkie** [comment]
800 molecules is a lot.
I guess from those you can generate many new and diverse molecules.

I am closing this issue, if you have more questions, you can contact me by e-mail (my professional e-mail is on all my recent articles).

**Comment by UnixJunkie** [comment]
Let's say you have molecules of two types: type A (interesting ones) and type B (uninteresting ones).
I think it is fine to generate molecules using just the ones of type A as your molecular training set.
I mean, if you want to find new molecules of type A.
